language: generic
# Precisaremos de permissão de superusuário para executar o docker
sudo: required
# Pedindo pra instalar o docker no container
services:
  - docker

before_install:
  - docker build -t paulodetarso/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true paulodetarso/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker-aws"
  env: "Dockeraws-env"
  bucket_name: "elasticbeanstalk-ca-central-1-673252907421"
  bucket_path: "docker-aws"
  on:
    branch: master
  access-key-id: $AWS_ACCESS_KEY
  secret-access-key: $AWS_SECRET_KEY